# Generated by Django 6.0.3 on 2026-03-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nulify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='piidetection',
            name='confidence',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='piidetection',
            name='detection_method',
            field=models.CharField(choices=[('regex', 'Regex'), ('nlp', 'NLP (NER)'), ('ml', 'ML Model')], default='regex', max_length=10),
        ),
        migrations.AddField(
            model_name='piidetection',
            name='sensitivity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10),
        ),
    ]
