# Generated by Django 6.0.3 on 2026-03-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nulify', '0002_piidetection_confidence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('upload', 'File Upload'), ('process', 'File Processing'), ('sanitize', 'Sanitization'), ('download', 'File Download'), ('download_original', 'Original File Download'), ('download_report', 'Report Download'), ('login', 'User Login'), ('logout', 'User Logout'), ('register', 'User Registration'), ('scan', 'Instant Scan'), ('settings', 'Settings Update')], max_length=30),
        ),
    ]
