# Generated by Django 4.2.7 on 2026-03-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nulify', '0003_uploadedfile_is_public_alter_auditlog_action_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='is_public',
        ),
        migrations.AddField(
            model_name='sanitizedfile',
            name='detection_source',
            field=models.CharField(choices=[('regex', 'Regex'), ('ner_ml', 'NER / ML (Deep Scan)')], default='regex', max_length=10),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
