# Generated by Django 4.2.7 on 2026-03-06 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nulify', '0004_remove_uploadedfile_is_public_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanitizationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_text', models.TextField(blank=True, default='')),
                ('data_file', models.FileField(blank=True, null=True, upload_to='requests/%Y/%m/')),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('method', models.CharField(choices=[('masking', 'Masking'), ('redaction', 'Redaction'), ('tokenization', 'Tokenization')], default='redaction', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_response', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nulify.sanitizedfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanitization_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'nulify_sanitization_request',
                'ordering': ['-created_at'],
            },
        ),
    ]
