# Generated by Django 6.0.3 on 2026-03-07 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nulify', '0003_alter_auditlog_action'),
        ('nulify', '0005_sanitizationrequest'),
    ]

    operations = [
    ]
