# Generated by Django 6.0.3 on 2026-03-07 06:24

import nulify.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nulify', '0005_sanitizationrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piidetection',
            name='original_value',
            field=nulify.models.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='sanitizationrequest',
            name='admin_response',
            field=nulify.models.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='sanitizationrequest',
            name='data_text',
            field=nulify.models.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='sanitizedfile',
            name='sanitized_text',
            field=nulify.models.EncryptedTextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='extracted_text',
            field=nulify.models.EncryptedTextField(blank=True, default=''),
        ),
    ]
